# Generated by Django 3.2.18 on 2023-04-15 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('topic', models.IntegerField(choices=[(1, 'Искусство'), (2, 'Бизнес'), (3, 'Дизайн'), (4, 'Экономика'), (5, 'Образование'), (6, 'Здоровье'), (7, 'Закон'), (8, 'Маркетинг'), (9, 'Наука'), (10, 'Самообразование'), (11, 'Спорт'), (12, 'Технологии'), (13, 'Путешествия')])),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.JSONField()),
                ('privacy', models.IntegerField(choices=[(1, 'Достуно всем'), (2, 'Ограниченный доступ'), (3, 'Приватно')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides_app.presentation')),
            ],
        ),
    ]
