# Generated by Django 3.2.18 on 2023-05-26 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.IntegerField(choices=[(1, 'Искусство'), (2, 'Бизнес'), (3, 'Дизайн'), (4, 'Экономика'), (5, 'Образование'), (6, 'Здоровье'), (7, 'Закон'), (8, 'Маркетинг'), (9, 'Наука'), (10, 'Самообразование'), (11, 'Спорт'), (12, 'Технологии'), (13, 'Путешествия')])),
                ('description', models.JSONField()),
                ('privacy', models.IntegerField(choices=[(1, 'Доступно всем'), (2, 'Приватно')])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('favorite', models.ManyToManyField(related_name='user_favorite', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68)),
                ('ordering', models.IntegerField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides_app.presentation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='slides_app.slide')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides_app.slide')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
                ('chosen_count', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides_app.question')),
                ('slides', models.ManyToManyField(to='slides_app.Slide')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('slide', 'email'), name='unique_slide_email_combination'),
        ),
    ]
