# Generated by Django 3.2.18 on 2023-04-27 13:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='slides',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=68), size=None),
        ),
    ]
